### PR TITLE
open() and sscanf() fixes

### LINKED ISSUE #61: openat without error check
In `get_procname` and `get_ppid`

### LINKED ISSUE #62: Missing oob check in sscanf
@martinpitt said:
> You also need to check that the len < sizeof(statbuf), as otherwise it's not nul terminated.
> You also have to set statbuf[len] = '\0' before calling sscanf to ensure it's nul terminated. The static only gives you a nulled array the first time, but afterwards if you first read a long and then a shorter file content you will get random junk at the end.

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #61 
Fixes #62 

 - [x] Builds on top of #64

### CODE REVIEW

File: fatrace.c [hunk 1]
```diff
@@ -322,11 +327,24 @@ static pid_t
...
+        return 0;
+    }
     ssize_t len = read (stat_fd, statbuf, sizeof (statbuf));
     close (stat_fd);
+    if (len < 0) {
+        warn ("failed to read /proc/PID/stat");
+        return 0;
+    }
+    /* buffer is static, and read() does not nul terminate */
+    statbuf[MAX(len, sizeof (statbuf) - 1)] = '\0';
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply fatrace.c]: Argh! Thanks, fixed.

File: fatrace.c [hunk 2]
```diff
@@ -38,8 +38,9 @@
 #include <sys/stat.h>
 #include <sys/statfs.h>
 #include <sys/fanotify.h>
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply fatrace.c:40]: OK, why not.

**Comment by martinpitt** [comment]
Ugh, ok, this apparently needs some work. I can't currently run the integration tests locally, they fail immediately. I need to debug that. But that's more of an afternoon/weekend thing.

**Comment by martinpitt** [comment]
@svenssonaxel I meant, doing the fixes that way. :grin:

**Comment by martinpitt** [comment]
- main already fails in a local Ubuntu 24.04 VM, which should be similar to the GitHub env.
- On my ostree system, fanotify is not that helpful for the root file system, and it reports /etc as /sysroot/ostree/deploy/fedora/deploy/12094cbaa3744f158f74dd9914e63b26462435acec31d081c8707154ae1f9c4b.0/etc/, and binaries as some hashed path in /sysroot/ostree/repo/objects/. So running the `fatrace` test on OSTree needs to be avoided, otherwise we'd have to dilute the test so much that it wouldn't be useful any more.
- Most tests work fine on my system, but `fatrace-exe` is broken, and the failure is unreadable:
```
+ jq -e 'select(
        .comm=="touch" and .path==$path and .exe==$touch_exe
        and .parents[0]=={"pid":$bash_pid,"comm":"bash","exe":$bash_exe}
        and .parents[1]=={"pid":$python_pid,"comm":"python3","exe":$python_exe}
        and .parents[2]=={"pid":$test_pid,"comm":"fatrace-exe","exe":$test_exe}
        and .parents[-1]=={"pid":1,"comm":$init_comm,"exe":$init_exe}
    )' --arg path /tmp/tmp.UsIShlOGcP/file.tmp --arg touch_exe /usr/bin/python3.13 --argjson bash_pid 29629 --arg bash_exe /usr/bin/bash --argjson python_pid 29628 --arg python_exe /usr/bin/python3.13 --argjson test_pid 29624 --arg test_exe /usr/bin/bash --arg init_comm systemd --arg init_exe /usr/lib/systemd/systemd
Not found in JSON log
```
... and then it prints a log which is absolutely not json, and even if it was, I wouldn't know what exactly it expects.

- This test suite harness is crap. With the recent feature additions it got extended a lot, which makes it even more crappy now. I should have rewritten it before all of that lands..

So in summary, I'll try to rebuild the tests using pytest.

**Comment by svenssonaxel** [comment]
> Making progress in https://github.com/martinpitt/fatrace/tree/refs/heads/pytest

Feel free to ping me for review.

**Comment by martinpitt** [comment]
I'd like to get in #64 tomorrow, and then rebase this.

File: fatrace.c [hunk 3]
```diff
@@ -302,18 +302,22 @@ print_json_str (const char* key, const char* value) {
 /* given an fd to /proc/PID and a buffer of size TASK_COMM_LEN, try to read the
    process name. Return true on success. */
 static bool
-get_procname (int proc_fd, char *procname, size_t procname_size) {
+get_procname (int proc_fd, pid_t pid, char *procname, size_t procname_size) {
     int fd = openat (proc_fd, "comm", O_RDONLY);
+    if (fd < 0) {
+        warn ("failed to open /proc/%u/comm", pid);
```
Comment (martinpitt) [inline fatrace.c:311]: This now introduces a lot of noise on stderr, but IMHO it's better to show why some results are missing.

File: fatrace.c [hunk 4]
```diff
@@ -302,18 +304,22 @@ print_json_str (const char* key, const char* value) {
...
+    }
     ssize_t len = read (fd, procname, procname_size - 1);
     close (fd);
-    if (len >= 0) {
-        while (len > 0 && procname[len-1] == '\n')
-            len--;
-        procname[len] = '\0';
-        return true;
+    if (len < 0) {
+        warn ("failed to read /proc/PID/comm");
```
Comment (svenssonaxel) [inline fatrace.c]: Perhaps do `/proc/%u/comm", pid` consistently.

File: fatrace.c (hunk 3 above)
Comment (svenssonaxel) [reply fatrace.c:311]: Maybe, but you now seem to disagree with your comments about removing the `problems` array in the `--json` patch. It'll be difficult to relate these printouts to the event in question.

File: fatrace.c [hunk 5]
```diff
@@ -322,11 +328,24 @@ static pid_t
 get_ppid (int proc_fd) {
     static char statbuf[4096];
     int stat_fd = openat (proc_fd, "stat", O_RDONLY);
+    if (stat_fd < 0) {
+        warn ("failed to open /proc/PID/stat");
```
Comment (svenssonaxel) [inline fatrace.c]: Use one warning scheme consistently; `/proc/%u/SOMETHING", pid` or `/proc/PID/SOMETHING"`

File: fatrace.c [hunk 6]
```diff
@@ -364,7 +383,7 @@ print_event (const struct fanotify_event_metadata *data,
             ppid = get_ppid (proc_fd);
 
         /* read process name */
-        if (get_procname (proc_fd, procname, sizeof (procname))) {
+        if (get_procname (proc_fd, data->pid, procname, sizeof (procname))) {
             procname_pid = data->pid;
             got_procname = true;
         }
```
Comment (svenssonaxel) [inline fatrace.c:390]: Perhaps the two `debug` calls below should be `warn`?

File: fatrace.c [hunk 7]
```diff
@@ -388,7 +407,7 @@ print_event (const struct fanotify_event_metadata *data,
 
         close (proc_fd);
     } else {
-        debug ("failed to open /proc/%i: %m", data->pid);
+        warn ("failed to open /proc/%i", data->pid);
     }
 
     /* /proc/pid/comm often goes away before processing the event; reuse previously cached value if pid still matches */
```
Comment (svenssonaxel) [inline fatrace.c:414]: Possibly missing `warn` calls below, in branch `} else if (option_json) {`, and also, the subsequent `} else {` might need an unconditional warning.

File: fatrace.c [hunk 8]
```diff
@@ -494,7 +513,7 @@ print_event (const struct fanotify_event_metadata *data,
             int ppid_dir_fd = open (printbuf, O_RDONLY | O_DIRECTORY);
             if (ppid_dir_fd >= 0) {
                 char p_procname[TASK_COMM_LEN];
-                if (get_procname (ppid_dir_fd, p_procname, sizeof (p_procname))) {
+                if (get_procname (ppid_dir_fd, ppid, p_procname, sizeof (p_procname))) {
                     if (option_json) {
                         putchar(',');
                         print_json_str("comm", p_procname);
```
Comment (svenssonaxel) [inline fatrace.c:520]: Missing warning in `if (option_exe) {` branch below.

File: fatrace.c [hunk 9]
```diff
@@ -38,8 +38,10 @@
 #include <sys/stat.h>
 #include <sys/statfs.h>
 #include <sys/fanotify.h>
-#include <sys/time.h>
+/* for MIN() */
+#include <sys/param.h>
 #include <sys/sysmacros.h>
+#include <sys/time.h>
```
Comment (svenssonaxel) [inline fatrace.c:46]: Why was this added in the commit `Fix buffer overflow in get_ppid()`?

Comment (martinpitt) [reply fatrace.c:46]: Just fixing the alphabetical ordering. I split it out into a separate commit and did that more thoroughly.

File: fatrace.c (hunk 3 above)
Comment (martinpitt) [reply fatrace.c:311]: With an output file it is; when streaming to the terminal it should be pretty clear. I tried to find the conversation in #49 and #51, but didn't see them any more :cry: 

I don't have a strong opinion about warn() vs. debug() here. I mostly care about the error checks.

File: fatrace.c (hunk 4 above)
Comment (martinpitt) [reply fatrace.c]: Right, fixed.

File: fatrace.c (hunk 5 above)
Comment (martinpitt) [reply fatrace.c]: Ack -- fixed by handing the pid to the function, so that it can print it.

File: fatrace.c (hunk 6 above)
Comment (martinpitt) [reply fatrace.c:390]: *nod* changed.

File: fatrace.c (hunk 7 above)
Comment (martinpitt) [reply fatrace.c:414]: Maaaybe? But not related to openat(), and it has fallbacks. I don't have time to investigate this deeply right now, I'm afraid.

File: fatrace.c (hunk 8 above)
Comment (martinpitt) [reply fatrace.c:520]: Not sure what you mean, but also not really related to openat() I think? Let's do that as a follow-up.

File: fatrace.c [hunk 10]
```diff
@@ -302,31 +305,48 @@ print_json_str (const char* key, const char* value) {
...
+        return 0;
+    }
     ssize_t len = read (stat_fd, statbuf, sizeof (statbuf));
     close (stat_fd);
+    if (len < 0) {
+        warn ("failed to read /proc/%u/stat", pid);
+        return 0;
+    }
+    /* buffer is static, and read() does not nul terminate */
+    statbuf[MIN(len, sizeof (statbuf) - 1)] = '\0';
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply fatrace.c:343]: We already ruled out `len < 0` in the code above. This ternary is correct, but MIN() is a shorter way to write it.

File: fatrace.c [hunk 11]
```diff
@@ -302,31 +305,48 @@ print_json_str (const char* key, const char* value) {
...
+
     pid_t ret;
-    if (len >= 0 && sscanf(statbuf, "%*d (%*[^)]) %*c %d", &ret) == 1)
+    if (sscanf(statbuf, "%*d (%*[^)]) %*c %d", &ret) == 1)
         return ret;
+    /* this *really* should not happen, kernel API change  */
+    warnx ("failed to parse /proc/%u/stat, please file a bug: %s", pid, statbuf);
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply fatrace.c:349]: This is defined to be a text file, it's fine.

File: fatrace.c (hunk 3 above)
Comment (svenssonaxel) [reply fatrace.c:311]: I also don't have a strong opinion, just bringing up context for your decision.

> I tried to find the conversation in https://github.com/martinpitt/fatrace/pull/49 and https://github.com/martinpitt/fatrace/pull/51, but didn't see them any more 😢

Expand all hidden and resolved comments, then search for "problems" and "add_problem".

File: fatrace.c (hunk 8 above)
Comment (svenssonaxel) [reply fatrace.c:520]: #67
